name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-lates
    strategy:
      matrix:
        python: '3.11'

      steps:
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
          name: Install Tox and any other packages
          run: pip install tox
          name: Run Tox
          run: tox -e py